### PR TITLE
(BKR-1435) Add the fedora28-64 platform

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by ScottGarman** [comment]
Fedora 28 is only going to be a 64-bit platform, so you can remove the i386 versions.

**Comment by ekinanp** [comment]
@ScottGarman Ok, I added the 32-bit one b/c the ticket mentioned both.

**Comment by ekinanp** [comment]
Updated the PR to only add Fedora 28, 64.

**Comment by ScottGarman** [comment]
Sorry for the confusion on the supported arches. Looks like the ticket generator was run with both arches listed, so all of the tickets are going to need to be updated.

**Pull request merged**
