### PR TITLE
(QENG-3489) Add Ubuntu 16.04 to beaker host generator data.

### PR DESCRIPTION
**Pull request by waynr**
This PR also
* fixes some test fixture borkage that resulted from the Cisco platform renames
* adds new test fixtures (it's not clear why these weren't in place previously)

### CODE REVIEW

**Comment by waynr** [comment]
@melissa @tvpartytonight this is ready for review.

**Comment by melissa** [comment]
:+1: looks good to me!

**Comment by melissa** [comment]
Is there anything blocking this being merged? And once it's in, does that mean we need a new release of this project?

**Comment by waynr** [comment]
@melissa ideally we would have two reviews, but please feel free to merge when you are ready.

And yes, we will need a new release for it to be usable--we have a jenkins job that does this.

**Comment by shermdog** [comment]
Seems legit to me - although I dislike having the cisco stuff combined with ubuntu.  Can @LuvCurves give a thumbs up on the cisco bits?

**Comment by waynr** [comment]
@shermdog the cisco stuff is a fix for test fixtures that would have otherwise caused PR tests to be red...I'm not sure why/how we missed that when we renamed the cisco platform aliases a few weeks back.

**Comment by tvpartytonight** [comment]
This looks good to me; I second @waynr's comments about the cisco bits. 👍

**Pull request merged**
