### PR TITLE
(QENG-3811) Add AIX and Solaris SPARC platforms

### PR DESCRIPTION
**Pull request by nwolfe**
Oh my god these fixture files (rageguy)

### CODE REVIEW

**Comment by nwolfe** [comment]
Yep, I changed 839 files

**Comment by nwolfe** [comment]
Ping @waynr @johnduarte for review.

Apologies for the terrible reviewing experience, GitHub gets slow when dealing with 839 changed files in a PR.

**Comment by nwolfe** [comment]
CC @kevpl

**Comment by nwolfe** [comment]
We still need https://tickets.puppetlabs.com/browse/QENG-3946 (arbitrary hypervisors) before we can completely get off static config files for the AIX and Solaris SPARC testing.

**Comment by johnduarte** [comment]
:+1:  FGTM. Thanks @nwolfe

**Comment by nwolfe** [comment]
> We still need https://tickets.puppetlabs.com/browse/QENG-3946 (arbitrary hypervisors) before we can completely get off static config files for the AIX and Solaris SPARC testing.

Done -- see #34

**Comment by waynr** [comment]
@nwolfe I just mentioned this in hipchat, but it's also worth mentioning on the PR--alphabetically sorting the platform mappings is an aesthatic change that would be better-suited to its own PR. Maybe it's not worth spending the time to separate it out here.

Once you remove the alphabetical sort, I think the best way to prevent shuffling fixtures around is to append new fixtures to the platform map--if I remember correctly.

**Comment by nwolfe** [comment]
I'm going to extract most of the PR into a separate PR that isolates the test fixture reordering, and also take a stab at improving the fixture generation code so it doesn't produce unnecessary and irrelevant fixture changes.

**Comment by nwolfe** [comment]
> I'm going to extract most of the PR into a separate PR that isolates the test fixture reordering, and also take a stab at improving the fixture generation code so it doesn't produce unnecessary and irrelevant fixture changes.

Done -- see #35

**Comment by nwolfe** [comment]
I'll rebase this PR once #35 is merged

**Comment by nwolfe** [comment]
@waynr Rebased.  Changed files down from 800 to 500 😄 

CC @kevpl

**Pull request merged**
