### PR TITLE
(QENG-3335) Don't identify centos as el in 'platform'

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by waynr** [comment]
This has too big a potential to break various projects' test suites and it looks like we can remove the `el-4` restriction mentioned in QENG-3335

**Comment by waynr** [comment]
This should really have some spec tests to validate the difference in behavior with the new flag.

@kylog what do you think of this approach so far? @rick, any thoughts?

**Comment by waynr** [comment]
Also, @colinPL @sschneid @kevpl

**Comment by sschneid** [comment]
:+1:

**Comment by kylog** [comment]
:+1: 

Do we want to add a deprecation warning for osinfo 0? Basically I'm thinking about a nudge for projects that will need to update themselves.

**Comment by waynr** [comment]
@kylog good idea, I added the deprecation warning.

**Comment by waynr** [comment]
ARgh...the deprecation warning isn't showing up...

**Comment by kylog** [comment]
@waynr and after this is merged, we'll then need a gem release of b-hg and then PRs against pup/fact/hi to specify `--osinfo-version 1`, correct? I can ready the latter.

**Comment by waynr** [comment]
@kylog that's correct, I'll fix the typo in the deprecation message in a bit here.

**Comment by waynr** [comment]
@kylog if this looks good to you, please feel free to merge. Spec tests are WIP but I don't think I'll be finishing them today.

**Comment by colinPL** [comment]
:+1:

**Comment by kylog** [comment]
Merged. 

@waynr when are you thinking about pushing a gem for this? If it's today, then I'll go ahead and queue the pup/fact/hi/pxp-agent PRs stat. If not, I'll put up a temp PR for ci-job-configs to drop centos-4 from the test matrix.

I'm fine either way tbh, but I'd like to get the puppet-agent daily pipelines back in action one way or the other.

**Pull request merged**
