### PR TITLE
(QENG-4176 & QENG-4180) Add OSX 10.12 and Windows 2016

### PR DESCRIPTION
**Pull request by smcelmurry**
Added OSX 10.12 (Sierra) and Windows Server 2016 to supported beaker-hostgenerator platforms

### CODE REVIEW

**Comment by smcelmurry** [comment]
@nwolfe

**Comment by nwolfe** [comment]
👍 

For these ridiculous test files, we've recently settled on regenerating them all (like 300 changes) but then only committing the files that include the new platform(s).  Looks like you've done that here.

**Comment by nwolfe** [comment]
@geoffnichols Just so you can see what "adding a platform to BHG" looks like.

Also so you can 👍 the platform strings.

Geoff, please merge if it looks good to you!

**Comment by geoffnichols** [comment]
👍

**Pull request merged**
