### PR TITLE
Add gnupg to debian9-64

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by smcelmurry** [comment]
Jenkins, test this please

**Comment by smcelmurry** [comment]
@mcanevet You'll need to update the spec test here to include `gnupg`:

https://github.com/puppetlabs/beaker-hostgenerator/blob/c691b742d1004676c758e220ab322fc323c3b80c/test/fixtures/per-host-settings/every-hypervisor.yaml#L54

**Comment by mcanevet** [comment]
@smcelmurry  done

**Comment by smcelmurry** [comment]
Jenkins, retest this please

**Pull request merged**
