### PR TITLE
(QENG-3335) Restrict osinfo v1 to centos only changes

### PR DESCRIPTION
**Pull request by kylog**
See https://tickets.puppetlabs.com/browse/BKR-662 for backstory.

### CODE REVIEW

**Comment by kylog** [comment]
Btw I pushed the PR straight to upstream rather than my fork in the "when in Rome ..." spirit. If that was stepping on anyone's toes though, please let me know!

**Comment by kylog** [comment]
I'm testing this right now in puppet on a couple TEST_TARGET variants.

**Comment by waynr** [comment]
@kylog pushing to a branch on the primary repo is strongly encouraged by our resident github expert, @rick. I have been trying to do this whenever possible for QE-managed projects so you are fine...as long as you don't force push ;).

**Comment by kylog** [comment]
I tried this with TEST_TARGETs of cent4 and cent5, i.e.

```
be rake ci:test:aio SHA=1.3.2 TESTS=tests/cycle_detection.rb TEST_TARGET=centos5-64a
be rake ci:test:aio SHA=1.3.2 TESTS=tests/cycle_detection.rb TEST_TARGET=centos4-64a
```

And both worked fine.

**Comment by waynr** [comment]
:+1:

**Pull request merged**
