### PR TITLE
(QENG-3275) Add support for 32-bit puppet on 64-bit windows

### PR DESCRIPTION
**Pull request by joshcooper**
This PR ensures `ruby_arch` defaults to the correct value based on the Windows OS architecture as the setting is required to run puppet, facter and pxp-agent acceptance on Windows hosts, and allows the caller to request 32-bit Puppet on 64-bit Windows, e.g. `windows2012r2-6432a`. Windows is unique in that there are three combinations, and we currently support all three:

* 32-bit Puppet on 32-bit Windows
* 32-bit Puppet on 64-bit Windows
* 64-bit Puppet on 64-bit Windows

### CODE REVIEW

**Comment by joshcooper** [comment]
Supercedes #9

**Comment by joshcooper** [comment]
@justinstoller comment from #9:

> Cool, I mean the data is syntactically correct, as long as it's the correct data. I've been pinged on what looks like a re-evaluation of our Windows 32 bit testing matrices elsewhere, so I wanted to broach the subject.

I'm not sure I totally understand your question.. So we've always installed 64-bit Puppet on 64-bit Windows and 32-bit Puppet on 32-bit Windows. The addition of `ruby_arch` just reaffirms what beaker already does, and is required by acceptance tests that need to know which puppet arch is installed.

I didn't add the 32-bit Puppet on 64-bit Windows combinations for desktop platforms, because FOSS doesn't test them. I'm not sure PE does, but would be easy to add if they do.

**Comment by justinstoller** [comment]
That wasn't so much a question as an explanation as to why I asked the previous question:
> Do we support 32bit Puppet on 64[bit] Desktop systems?

I had just seen discussions around: https://docs.google.com/document/d/1Ot6zW5aEX2P8s8JVppokXLOJ851c3do8XzwdCVHoSkQ/edit#heading=h.6yg2l174jlfe

That made me wonder if we were going to be reworking our test matrices. And if in reworking them possibly including 32 bit puppet on 64 bit desktop OSes. And if that was a possibility, then would we want to include the same 32bit on 64bit hostgenerator option strings for desktop OSes that we're including for server OSes in the PR?

I think if there's confusion around that though I'm happy to merge this PR for updating Windows Server OSes with the 32bit on 64bit values and if needed later on update the Windows Desktop OSes.

**Comment by waynr** [comment]
:+1:

**Comment by joshcooper** [comment]
> That made me wonder if we were going to be reworking our test matrices. And if in reworking them possibly including 32 bit puppet on 64 bit desktop OSes. And if that was a possibility, then would we want to include the same 32bit on 64bit hostgenerator option strings for desktop OSes that we're including for server OSes in the PR?

I want to deprecate, stop testing, and eventually remove support for 32-bit puppet on 64-bit windows. We currently test 32-bit puppet on 2012r2 and 2008r2 (both 64-bit), and this PR handles those combinations, so that we can at least support what we currently test. That said, I don't want to expand the set of 32/64 combinations to desktop platforms, since the goal is the opposite.

When we eventually remove 32-bit puppet from 64-bit windows, we will need to select a replacement 32-bit windows, and our choices are either 2008 non-R2 or desktop. Of those, we only have windows 10 32-bit in the vmpooler, so we will likely adopt that, but that will be 32-bit puppet on 32-bit windows.

**Pull request merged**
